import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

// --- COMPLETE TRANSLATION DATA ---
const translations = {
  en: {
    // Header - menu 
    'nav.services': 'Services',
    'nav.strategy': 'Strategy',
    'nav.about': 'About Us',
    'nav.partnerships': 'Partnerships',
    'nav.governance': 'Governance',
    'nav.funds':'Funds',
    'nav.careers': 'Careers',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',
    'nav.investment': 'Investment Programmes',
    'nav.impact': 'Our Impact',
    'nav.protocol': 'Our Engagement Protocol',
    
    //--------------------------------HOMEPAGE--------------------------------
    // Hero
    'hero.title': 'Architecting',
    'hero.title1': 'the World ',
    'hero.title2': 'of Tomorrow',
    'hero.description': "The future isn't found. Its built. Xhiva deploys strategic capital into the disruptive technologies, critical infrastructure, and sustainable initiatives that will define the next century. We don't just invest in the world; we invest in the world of tomorrow.",
    'hero.cta': 'Discover Our Global Impact',
    'hero.viewDemo': 'Learn More',

    'home.bridgeText': 'Driver of Global Progress',

    // Homepage (Leadership Section)
    'homepage.leadership.subtitle': 'Our Leadership',
    'homepage.leadership.title': 'The Stewards of Capital',
    'homepage.leadership.description': 'Trust is the foundation of every relationship we build. We believe it is essential for our partners to know those who are personally committed to safeguarding their interests and upholding our firm\'s principles.',
    
    // About Us Section (Homepage)
    'about.subtitle': 'Architects of Global Progress',
    'about.description': "Capital is a current. Policy is a rudder. Innovation is the wind. Xhiva operates at the confluence of all three, navigating global complexity to redefine industries and build generational value. We don't just participate in the market—we aim to shape it.",
    'about.learnMore': 'Learn More', 
    'about.feature1-title': "Global Leadership",
    'about.feature1-desc': "Leading investment strategies worldwide with unparalleled market intelligence.",
    'about.feature2-title': "Institutional Excellence", 
    'about.feature2-desc': "Delivering exceptional results for institutional clients and sovereign funds.",
    'about.feature3-title': "Expert Network",
    'about.feature3-desc': "World-class professionals spanning finance, technology, and policy across our global operations.",

    // Strategy Section (Homepage)
    'strategy.subtitle': 'INVESTMENT STRATEGY',
    'strategy.title': 'A Disciplined Framework for Exclusive Opportunities',
    'strategy.description': 'Our investment strategy is devised for qualified private investors, family offices, ultra-high-net-worth individuals, institutional investors, and sovereign entities who seek access to institutional-grade programmes within a framework of robust compliance, capital preservation, and risk-adjusted performance.',
    'strategy.card1.title': 'Strategic Origination',
    'strategy.card1.description': 'We source opportunities directly through our established position with sovereign bodies and premier institutions.',
    'strategy.card2.title': 'Prudential Assessment & Vetting',
    'strategy.card2.description': 'We conduct a forensic examination of structural components, asset provenance, counterparty integrity, regulatory compliance, and geo-political environment.',
    'strategy.card3.title': 'Tailored Governance Structures',
    'strategy.card3.description': 'We construct tailored legal and financial vehicles with strict adherence to statutes and the integration of capital preservation controls.',
    'strategy.card4.title': 'Fiduciary Stewardship & Governance',
    'strategy.card4.description': 'ESG integration with impact measurement for responsible long-term value creation.',
    'strategy.image.alt': 'Global Funds Strategy',
    'strategy.image.title': 'Our Disciplined, Four-Pillar Framework',
    'strategy.image.description': 'These structured programmes are not publicly advertised and are accessible only through a formal engagement protocol.',
    'strategy.image.button': 'Discover more',

    // Interactive Section (Homepage)
    'interactive.title1':'Capital with Vision.',
    'interactive.title2':'Impact with Purpose.',
    'interactive.description':"We believe the most profound value is created at the intersection of visionary ideas, strategic capital, and global impact. We don't just fund companies—we architect the foundations of the future.",
    'interactive.block1-title':'Founder & Managing Partner',
    'interactive.block1-description':"A brief, dignified biography focusing on 20+ years of experience in international finance, prior roles within sovereign advisory or top-tier banking institutions, and a concluding sentence on their personal philosophy regarding patient capital and legacy preservation.",
    'interactive.block2-title':'Head of Structuring & Compliance',
    'interactive.block2-description':"A biography highlighting deep expertise in cross-border regulatory frameworks, legal structuring for complex financial instruments, and a commitment to impeccable governance as the core of risk mitigation.",
    'interactive.block3-title':'Head of Global Origination',
    'interactive.block3-description':"A biography detailing an extensive global network, experience in geo-political analysis, and the ability to source and vet unique, off-market opportunities with discretion and precision.",

    // Carousel Section (Homepage)
    'carusel.block1-title':'Bespoke Architecture',
    'carusel.block1-description':'Explore our suite of tailored services, engineered for the unique complexities of our partners.',
    'carusel.block1-button':'Discover Services',
    'carusel.block2-title':'The Engines of Tomorrow',
    'carusel.block2-description':'Delve into our portfolio of specialized funds, each designed to harness a specific global megarend.',
    'carusel.block2-button':'Explore Funds',
    'carusel.block3-title':'Join the Vanguard',
    'carusel.block3-description':"We are a destination for the world's elite talent. Discover a career that places you at the frontier of progress.",
    'carusel.block3-button':'View Careers',
    'carusel.block4-title':'Strategic Alliances',
    'carusel.block4-description':'We forge powerful partnerships to amplify impact and create synergistic value across our entire ecosystem.',
    'carusel.block4-button':'Become a Partner',
    'carusel.block5-title':'Principled Governance',
    'carusel.block5-description':'Our commitment to robust governance and ethical frameworks is the bedrock of our long-term vision.',
    'carusel.block5-button':'Learn About Governance',

    // Call to Action Section (Homepage)
    'cta.title.line1': 'BEGIN YOUR',
    'cta.title.accent': 'JOURNEY',
    'cta.description': "Join the world's most sophisticated investors in accessing institutional-grade investment opportunities and personalized wealth management solutions.",
    'cta.button.primary': 'REQUEST CONSULTATION',
    'cta.button.secondary': 'EXPLORE FUNDS',
    'cta.contact1.title': 'EMAIL CONTACT',
    'cta.contact1.text': 'investments@xhiva.com',
    'cta.contact2.title': 'PHONE CONTACT',
    'cta.contact2.text': 'Available upon request',
    'cta.contact3.title': 'GLOBAL OFFICES',
    'cta.contact3.text': 'Six continents',
    'cta.notice.title': 'Institutional Access',
    'cta.notice.text': 'XHIVA services are exclusively available to qualified institutional investors and high-net-worth individuals meeting stringent regulatory and investment threshold requirements. All investments are subject to comprehensive due diligence and suitability assessments.',

    // Footer Translations
    'footer.company': 'Company',
    'footer.investorRelations': 'Investor Relations',
    'footer.services': 'Organisation',
    'footer.globalFunds': 'Global Funds',
    'footer.legal': 'Legal',
    'footer.compliance': 'Compliance',
    'footer.connect': 'Connect',
    'footer.stakeholderLogin': 'Stakeholder Login',
    'footer.globalOffices': 'Global Offices',
    'footer.pressInquiries': 'Press Inquiries',
    'footer.logoAlt': 'XHIVA Logo',
    'footer.logoText': 'XHIVA',
    'footer.brandDescription': 'Architecting the world of tomorrow through strategic global investments and transformative partnerships.',
    'footer.newsletterTitle': 'Stay Informed',
    'footer.newsletterDescription': 'Receive exclusive insights and updates on global market trends and investment opportunities.',
    'footer.emailPlaceholder': 'Enter your email',
    'footer.subscribe': 'Subscribe',
    'footer.newsletterNote': 'Institutional investors and qualified entities only. Subject to verification.',
    'footer.regulatedBy': 'Regulated by:',
    'footer.disclaimer': 'Legal Disclaimer',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': '© 2025 Xhiva. All rights reserved.',
    'footer.language.es': 'Español',
    'footer.language.en': 'English',

    //------------------------------------------------SUBPAGES-------------------------------------------------------
    //Protocol subpage : 
    'protocol.preTitle': 'Engagement Protocol',
    'protocol.title': 'The Client Inception Process',
    'protocol.step1.title': 'Initial Contact',
    'protocol.step1.description': 'Submit a secure enquiry form detailing your investor status.',
    'protocol.step2.title': 'Eligibility Verification',
    'protocol.step2.description': 'We conduct preliminary KYC/AML checks to confirm qualification.',
    'protocol.step3.title': 'Confidential Discussion',
    'protocol.step3.description': 'Schedule a secure call to discuss objectives and alignment.',
    'protocol.step4.title': 'Formal Agreement',
    'protocol.step4.description': 'Execute NDAs and legal documents for programme access.',
    'protocol.step5.title': 'Programme Execution',
    'protocol.step5.description': 'Structured participation with ongoing stewardship.',

    //INVESTMENT
    'investment.preTitle': 'Investment Programmes',
    'investment.title': 'Access to Exclusive Investment Tiers',
    'investment.intro1': 'Our unique positioning within the global geo-political and regulatory landscape allows us to arrange access to structured investment opportunities that are typically reserved for institutional or sovereign-level participants.',
    'investment.intro2': 'Participation is by invitation only, following a comprehensive client inception process. The following categories represent the types of programmes with which we work, though availability is dynamic and subject to strict protocols.',
    'investment.cta': 'To explore available programmes, qualified investors may initiate our confidential Engagement Protocol.',
    'investment.details.description': 'Description',
    'investment.details.access': 'Access Level',
    'investment.details.duration': 'Typical Duration',
    'investment.details.risk': 'Risk Profile (Mitigated)',
    'investment.program1.title': 'Placements Linked to Central Banks',
    'investment.program1.description': 'Secure structures delivering consistent, risk-adjusted returns based on sovereign-backed mechanics.',
    'investment.program1.access': 'Invitation only; sovereign/institutional priority.',
    'investment.program1.duration': 'Medium to long-term.',
    'investment.program1.risk': 'Low; emphasized capital preservation.',
    'investment.program2.title': 'Trading Programmes Affiliated with Governments',
    'investment.program2.description': 'Linked to regulated platforms supporting national funding initiatives.',
    'investment.program2.access': 'Restricted to qualified entities.',
    'investment.program2.duration': 'Variable, aligned with mandates.',
    'investment.program2.risk': 'Moderate; with regulatory safeguards.',
    'investment.program3.title': 'Limited Access & Pilot Programmes',
    'investment.program3.description': 'Innovative, early-stage opportunities with unique terms and potential upside.',
    'investment.program3.access': 'By special invitation.',
    'investment.program3.duration': 'Short to medium-term.',
    'investment.program3.risk': 'Higher; offset by bespoke mitigations.',
    'investment.program4.title': "Fixed-Term or 'Bullet' Programmes",
    'investment.program4.description': 'High-yield potential over defined periods; time-sensitive.',
    'investment.program4.access': 'Highly selective.',
    'investment.program4.duration': 'Short-term.',
    'investment.program4.risk': 'Variable; includes indemnities where applicable.',

    //Impact  page 
    'impact.preTitle': 'Our Impact',
    'impact.title': 'A Mandate Beyond Profit: Fostering Stability and Progress',
    'impact.intro1': 'We believe the most sophisticated form of investment is one that achieves a dual mandate: the intelligent growth of capital and the deliberate advancement of society. Our purpose is defined by this synergy.',
    'impact.intro2': 'Our impact is not an afterthought; it is embedded in our origination strategy. We seek opportunities where capital can be deployed to:',
    'impact.conclusion': 'For our clients, this approach means their capital is part of a larger, more meaningful legacy—one that builds enduring value for their portfolios and for the world.',
    'impact.economic.title': 'Reinforce Economic Foundations',
    'impact.economic.description': 'By participating in programmes that support sovereign wealth management and national funding initiatives, we contribute to the long-term stability that is essential for nations to thrive. This may involve the modernisation of critical infrastructure or the strengthening of a country\'s trade capacity.',
    'impact.humanitarian.title': 'Enable Humanitarian Progress',
    'impact.humanitarian.description': 'We align our efforts with globally recognised goals, such as those outlined by the UN Sustainable Development Goals. Our involvement can channel significant capital towards initiatives that have a tangible, positive effect on societal well-being, from advancements in public health to improvements in food security.',

    // About Us Subpage
    'about.page.preTitle': 'About Us',
    'about.page.mainTitle': 'Architects of Stability and Value at the Apex of Global Finance',
    'about.page.title':'Our Position in Global Finance',
    'about.page.intro1': 'Welcome. We operate at the confluence of central banking, sovereign government initiatives, and private capital. With an operational presence in over 63 jurisdictions, our firm serves a critical role in the global financial architecture.',
    'about.page.intro2': 'Our engagements frequently require us to act in fiduciary capacities such as an escrow agent, compliance overseer, or structuring partner for sovereign entities and premier regulated financial institutions. This unique position grants us privileged access to opportunities that are, by their nature, wholly unavailable in the public markets.',
    'about.philosophy.title': 'A Philosophy of Stewardship',
    'about.philosophy.text': 'Capital is more than a commodity; it is a catalyst. In the right hands, guided by a disciplined philosophy, it has the power not only to grow but to build, stabilise, and endure for generations. Our firm was founded on this principle. We believe that true stewardship extends beyond the delivery of risk-adjusted returns; it demands an unwavering commitment to the preservation of legacy and the creation of positive, lasting impact. We do not simply manage assets; we enter into long-term partnerships built on trust, discretion, and a shared understanding of what it means to build resilient value in a complex world.',
    'about.mission.title': 'Our Mission',
    'about.mission.text1': 'Our Mission is twofold: to structure and deliver impeccably governed investment programmes that provide measured, risk-adjusted returns, whilst simultaneously fulfilling broader mandates for economic stabilisation and meaningful humanitarian impact.',
    'about.mission.text2': 'Every action we take is guided by three unwavering principles:',
    'about.principles.item1.title': 'Stringent Due Diligence',
    'about.principles.item1.text': 'We meticulously vet every opportunity, scrutinising asset provenance, counterparty integrity, and geo-political context.',
    'about.principles.item2.title': 'Uncompromising Transparency',
    'about.principles.item2.text': 'We believe trust is built upon clarity. Our clients receive transparent reporting within the bounds of confidentiality agreements.',
    'about.principles.item3.title': 'Unyielding Compliance',
    'about.principles.item3.text': 'Adherence to the highest international standards of regulatory compliance is not merely a policy—it is the bedrock of our operations.',
    'about.page.footer': 'We are more than asset managers; we are trusted stewards of capital, dedicated to building resilient value for our select clientele.',

    // Services Subpage
    'services.preTitle': 'INSTITUTIONAL SERVICES',
    'services.title': 'An Integrated Suite of Financial Services',
    'services.details.focusTitle': 'Focus',
    'services.details.approachTitle': 'Approach',
    'services.details.deliveryTitle': 'Delivery',
    'services.item1.title': 'Asset Management',
    'services.item1.subtitle': 'Portfolio Solutions',
    'services.item1.description': 'Sophisticated management of diversified global portfolios with institutional-grade strategies.',
    'services.item1.details.focus': 'Comprehensive Investment Management',
    'services.item1.details.approach': 'Multi-asset class portfolio construction, dynamic rebalancing, and advanced risk frameworks.',
    'services.item1.details.delivery': 'Real-time institutional-grade reporting and dedicated relationship management.',
    'services.item2.title': 'Custom Portfolio Construction',
    'services.item2.subtitle': 'Bespoke Solutions',
    'services.item2.description': 'Tailored investment strategies engineered to align with unique objectives and risk profiles.',
    'services.item2.details.focus': 'Personalized Investment Architecture',
    'services.item2.details.approach': 'Machine learning optimization, tax-efficient strategies, and alternative investment integration.',
    'services.item2.details.delivery': 'Customized reporting schedules with dedicated managers and direct communication channels.',
    'services.item3.title': 'Wealth & Succession Planning',
    'services.item3.subtitle': 'Legacy Solutions',
    'services.item3.description': 'Strategic wealth preservation and transfer solutions designed for multi-generational impact.',
    'services.item3.details.focus': 'Generational Wealth Strategies',
    'services.item3.details.approach': 'Dynasty trust implementation, estate planning optimization, and sophisticated tax mitigation structures.',
    'services.item3.details.delivery': 'Annual strategic reviews with quarterly assessments and dedicated family office teams.',
    'services.item4.title': 'Fiduciary & Trust Services',
    'services.item4.subtitle': 'Institutional Stewardship',
    'services.item4.description': 'Professional fiduciary oversight providing institutional-level governance for complex structures.',
    'services.item4.details.focus': 'Institutional Asset Stewardship',
    'services.item4.details.approach': 'Corporate trustee services with investment committee oversight and comprehensive regulatory compliance.',
    'services.item4.details.delivery': 'Continuous monitoring with real-time oversight and direct access to senior fiduciary professionals.',
    'services.item5.title': 'ESG & Impact Investing',
    'services.item5.subtitle': 'Sustainable Integration',
    'services.item5.description': 'Advanced ESG integration and impact measurement frameworks delivering measurable returns.',
    'services.item5.details.focus': 'Sustainable Investment Integration',
    'services.item5.details.approach': 'Proprietary ESG scoring, comprehensive impact measurement, and climate risk assessment.',
    'services.item5.details.delivery': 'Semi-annual impact reporting, quarterly updates, and dedicated ESG specialists.',
    'services.item6.title': 'Direct Co-Investment',
    'services.item6.subtitle': 'Exclusive Access',
    'services.item6.description': 'Privileged access to proprietary investment opportunities typically reserved for institutions.',
    'services.item6.details.focus': 'Exclusive Deal Access',
    'services.item6.details.approach': 'Private equity co-investments with reduced fee structures and infrastructure project participation.',
    'services.item6.details.delivery': 'Deal-by-deal basis, rapid deployment, and priority access to proprietary opportunities.',
    
    // Funds Subpage
    'funds.subtitle': 'OUR GLOBAL FUNDS',
    'funds.title': 'The Engines of Global Progress',
    'funds.description': 'A curated portfolio of specialized investment vehicles, each engineered to capitalize on a distinct global megatrend. Our funds provide qualified investors with access to proprietary strategies and institutional-grade opportunities across the entire risk-return spectrum.',
    'funds.videoFallback': 'Your browser does not support the video tag.',
    'funds.details.philosophy': 'Philosophy',
    'funds.details.strategy': 'Core Strategy',
    'funds.details.allocation': 'Primary Allocation',
    'funds.details.financials': 'Financials',
    'funds.details.riskProfile': 'Risk Profile',
    'funds.details.horizon': 'Horizon',
    'funds.details.targetIRR': 'Target IRR',
    'funds.item1.name': 'The Genesis Growth Fund',
    'funds.item1.focus': 'Early-stage disruptive technology companies',
    'funds.item1.philosophy': 'We believe the most significant returns are generated by investing early in technologies that fundamentally reshape industries. Our thesis is built on identifying visionary founders and providing the capital and strategic guidance to achieve exponential growth.',
    'funds.item1.strategy': 'Venture capital and growth equity investments in AI, quantum computing, and synthetic biology.',
    'funds.item1.allocation': 'Primarily non-public equities and convertible notes.',
    'funds.item1.riskProfile': 'High',
    'funds.item1.investmentHorizon': '10+ Years',
    'funds.item1.targetIRR': '30-35% (net)',
    'funds.item2.name': 'The Sovereign Infrastructure Fund',
    'funds.item2.focus': 'Large-scale government and public-private infrastructure projects',
    'funds.item2.philosophy': 'Modern civilization is built on a foundation of reliable infrastructure. We seek to generate stable, long-term returns by financing the essential assets that power economies, from digital networks to sustainable energy grids.',
    'funds.item2.strategy': 'Direct financing and co-investment in transportation, energy grids, and digital infrastructure.',
    'funds.item2.allocation': 'Mix of long-duration debt, private equity, and real assets.',
    'funds.item2.riskProfile': 'Low-Moderate',
    'funds.item2.investmentHorizon': '15-20 Years',
    'funds.item2.targetIRR': '8-12% (net)',
    'funds.item3.name': 'The Global Impact Fund',
    'funds.item3.focus': 'Humanitarian and sustainable development projects',
    'funds.item3.philosophy': 'We hold that financial success and positive social change are not mutually exclusive. This fund targets ventures that provide measurable improvements in human well-being and environmental sustainability while delivering competitive returns.',
    'funds.item3.strategy': 'Investing in renewable energy, food security, and healthcare access in emerging markets.',
    'funds.item3.allocation': 'Blend of social impact bonds, private equity, and sustainable real estate.',
    'funds.item3.riskProfile': 'Moderate',
    'funds.item3.investmentHorizon': '7-10 Years',
    'funds.item3.targetIRR': '15-18% (net)',
    'funds.item4.name': 'The Quantum Alpha Fund',
    'funds.item4.focus': 'Advanced quantitative and algorithmic trading',
    'funds.item4.philosophy': 'The global markets are a complex system of information. By leveraging sophisticated AI and quantitative models, we aim to identify and capitalize on transient market inefficiencies that are invisible to the human eye.',
    'funds.item4.strategy': 'AI-driven models to identify market inefficiencies across global capital markets.',
    'funds.item4.allocation': 'Multi-asset portfolio including equities, fixed income, currencies, and commodities.',
    'funds.item4.riskProfile': 'High',
    'funds.item4.investmentHorizon': 'Short to Medium-Term',
    'funds.item4.targetIRR': '20-25% (Alpha-driven)',
    'funds.item5.name': 'The Real Asset & Commodities Fund',
    'funds.item5.focus': 'Tangible assets with intrinsic value',
    'funds.item5.philosophy': 'In an increasingly digital world, tangible assets provide a fundamental store of value and a hedge against inflation. This fund secures ownership of critical real-world resources that are essential for global industry and consumption.',
    'funds.item5.strategy': 'Strategic acquisition in energy, precious metals, and agriculture.',
    'funds.item5.allocation': 'Primarily physical commodities, real estate, and futures contracts.',
    'funds.item5.riskProfile': 'Moderate-High',
    'funds.item5.investmentHorizon': '5-10 Years',
    'funds.item5.targetIRR': '12-16% (net)',
    'funds.item6.name': 'The Bio-Revolution Fund',
    'funds.item6.focus': 'Next-generation biotechnology and healthcare solutions',
    'funds.item6.philosophy': 'The convergence of biology and technology is creating an unprecedented wave of innovation in human health. We invest in companies at the forefront of this revolution, targeting breakthroughs in longevity, personalized medicine, and disease eradication.',
    'funds.item6.strategy': 'Investments in gene editing, personalized medicine, and life-extension technologies.',
    'funds.item6.allocation': 'Mix of venture capital, public equities, and royalty-bearing instruments.',
    'funds.item6.riskProfile': 'Very High',
    'funds.item6.investmentHorizon': '10-15 Years',
    'funds.item6.targetIRR': '35%+ (net)',
    'funds.item7.name': 'The Digital Frontier Fund',
    'funds.item7.focus': 'Architecture of the next-generation internet',
    'funds.item7.philosophy': 'Decentralization and digital ownership are the foundational pillars of the next internet age. We invest in the core protocols, infrastructure, and applications that will power this new, more equitable digital economy.',
    'funds.item7.strategy': 'Investing in DeFi, blockchain infrastructure, and cybersecurity technologies.',
    'funds.item7.allocation': 'Primarily digital assets, venture capital, and private equity.',
    'funds.item7.riskProfile': 'Very High',
    'funds.item7.investmentHorizon': '7-10 Years',
    'funds.item7.targetIRR': '40%+ (net)',
    'funds.item8.name': 'The Global Stability Fund',
    'funds.item8.focus': 'Capital preservation and risk mitigation',
    'funds.item8.philosophy': 'Wealth preservation is the cornerstone of lasting prosperity. This fund is engineered to protect capital and provide stable returns across all market cycles, acting as a defensive anchor for a diversified portfolio.',
    'funds.item8.strategy': 'Multi-asset class fund for all market conditions with sovereign debt and safe-haven assets.',
    'funds.item8.allocation': 'Balanced mix of government bonds, inflation-linked securities, and defensive equities.',
    'funds.item8.riskProfile': 'Low',
    'funds.item8.investmentHorizon': 'Long-Term',
    'funds.item8.targetIRR': '5-7% (net)',
    'funds.item9.name': 'The Emerging Markets Ascendancy Fund',
    'funds.item9.focus': 'High-growth economies',
    'funds.item9.philosophy': "The world's economic center of gravity is shifting. We identify and invest in the next generation of industry leaders in Asia, Africa, and Latin America, capitalizing on demographic shifts and rapid consumer class growth.",
    'funds.item9.strategy': 'Identifying next-wave industry leaders in Asia, Africa, and Latin America.',
    'funds.item9.allocation': 'Mix of public and private equities, sovereign debt, and real estate.',
    'funds.item9.riskProfile': 'High',
    'funds.item9.investmentHorizon': '8-12 Years',
    'funds.item9.targetIRR': '22-28% (net)',

    // Partnerships Subpage
    'partnerships.preTitle': 'BEYOND BORDERS',
    'partnerships.title': 'Global Partnership Network',
    'partnerships.item1.category': 'SOVEREIGN WEALTH FUNDS',
    'partnerships.item1.description': 'Strategic partnerships with national investment authorities and sovereign entities across major economies.',
    'partnerships.item1.focus': 'Government Relations',
    'partnerships.item2.category': 'INSTITUTIONAL INVESTORS',
    'partnerships.item2.description': 'Collaborative relationships with pension funds, endowments, and insurance companies worldwide.',
    'partnerships.item2.focus': 'Institutional Capital',
    'partnerships.item3.category': 'GLOBAL BANKS',
    'partnerships.item3.description': 'Core banking partnerships with tier-one financial institutions for capital markets access.',
    'partnerships.item3.focus': 'Banking Infrastructure',
    'partnerships.item4.category': 'TECHNOLOGY PARTNERS',
    'partnerships.item4.description': 'Innovation alliances with leading fintech companies and technology infrastructure providers.',
    'partnerships.item4.focus': 'Digital Innovation',
    'partnerships.item5.category': 'REGULATORY BODIES',
    'partnerships.item5.description': 'Compliance partnerships with financial regulatory authorities across all operating jurisdictions.',
    'partnerships.item5.focus': 'Regulatory Excellence',
    'partnerships.item6.category': 'RESEARCH INSTITUTIONS',
    'partnerships.item6.description': 'Academic partnerships with leading universities and think tanks for market research and analysis.',
    'partnerships.item6.focus': 'Research Excellence',
    'partnerships.cta.title': 'Ready to Build the Future?',
    'partnerships.cta.subtitle': "Let's collaborate and create value together. We're looking for innovative partners to join our mission.",
    'partnerships.cta.button': 'Become a Partner',
    
    //Strategy subpage
    'strategy.page.preTitle': 'Our Strategies',
    'strategy.page.title': 'Our Investment Strategy',
    'strategy.page.subtitle': 'A Disciplined Framework for Exclusive Opportunities',
    'strategy.page.intro': 'Our investment strategy is devised for qualified private investors, family offices, and high-net-worth individuals who seek access to institutional-grade programmes within a framework of robust compliance, capital preservation, and exceptional, risk-adjusted performance.',
    'strategy.page.disclaimer': 'These structured programmes are not publicly advertised and are accessible only through a formal engagement protocol.',
    'strategy.approach.title': 'Our Strategic Approach',
    'strategy.approach.intro': 'Our strategy is not based on market speculation but upon disciplined access to pre-vetted, high-level financial programmes. Each potential engagement is evaluated on its own merits, with a focus on:',
    'strategy.approach.item1.title': 'Asset Provenance & Security',
    'strategy.approach.item1.description': 'We begin by verifying the origin and integrity of all assets, ensuring a clean and compliant foundation for any transaction.',
    'strategy.approach.item2.title': 'Regulatory Alignment',
    'strategy.approach.item2.description': 'Our structures are tailored to meet and exceed the regulatory obligations of all participating jurisdictions, ensuring a smooth and secure execution.',
    'strategy.approach.item3.title': 'Strategic Objective Matching',
    'strategy.approach.item3.description': 'We work to understand the core goals of our counterparties—be they sovereign wealth stabilisation or private capital growth—and align our programmes accordingly.',
    'strategy.governance.title': 'Governance, Risk, and Structuring',
    'strategy.governance.intro': 'Whilst no investment is entirely without risk, our entire operational model is designed to mitigate such risks. All programmes we arrange are structured in direct collaboration with regulated financial institutions, licensed platform operators, and, in many cases, governmental entities. Our commitment to protecting client interests includes:',
    'strategy.governance.item1.title': 'Robust Due Diligence',
    'strategy.governance.item1.description': 'Comprehensive background checks and compliance protocols on all parties.',
    'strategy.governance.item2.title': 'Transparent Funding Protocols',
    'strategy.governance.item2.description': 'Clear verification of fund origin and ownership (KYC/AML).',
    'strategy.governance.item3.title': 'Bespoke Capital Structuring',
    'strategy.governance.item3.description': 'Tailored legal and financial vehicles designed for optimal regulatory compliance and asset protection.',
    'strategy.govergannce.item4.title': 'Optional Risk Mitigation',
    'strategy.governance.item4.description': 'Access to mechanisms such as third-party oversight, indemnities, and other institutional safeguards.',
    'strategy.conclusion.text': 'Where required, our team is equipped to advise upon and establish the appropriate legal and financial entities to meet specific jurisdictional or strategic objectives, ensuring our clients are perfectly positioned for participation.',


    //career 

 "careers.preTitle": "CAREER OPPORTUNITIES",
  "careers.title": "Advance Your Career with an Industry Leader",
  "careers.introText": "We invite qualified, dedicated professionals to explore career opportunities with our firm. We are committed to attracting and developing top talent to drive innovation and maintain our standard of excellence in the global financial sector.",

  "careers.block1.title": "Commitment to Innovation",
  "careers.block1.text": "Engage with industry experts in the development of cutting-edge financial technologies and strategic solutions.",

  "careers.block2.title": "Significant Global Influence",
  "careers.block2.text": "Your contributions will directly support a platform integral to international economic stability and sustainable growth.",

  "careers.block3.title": "A Foundation of Integrity",
  "careers.block3.text": "We operate within a framework of rigorous ethical standards, ensuring a transparent and principled professional environment for all employees.",

  "careers.form.heading": "Submit Your Application",
  "careers.form.nameLabel": "Full Name",
  "careers.form.emailLabel": "Email Address",
  "careers.form.positionLabel": "Position of Interest",
  "careers.form.coverLetterLabel": "Cover Letter",
  "careers.form.fileTitle": "Attach Supporting Documents (Max 5)",
  "careers.form.selectFiles": "Select Files",
  "careers.form.limitReached": "File Limit Reached",
  "careers.form.submitButton": "Submit Application",
  "careers.form.sendingButton": "Submitting...",
  "careers.form.dragDrop": "Drag and drop documents here, or",
  "careers.form.browseFiles": "select from your device",
  "careers.form.fileSupport": "Supported formats",
  "careers.form.maxSize": "Maximum size",
  "careers.form.perFile": "per file",

  "careers.modal.limitTitle": "File Limit Exceeded",
  "careers.modal.limitMessage": "The maximum number of attachments (5) has been reached. Please remove a file to add another.",
  "careers.modal.fileTypeTitle": "Unsupported File Type",
  "careers.modal.fileTypeMessage": "The file",
  "careers.modal.fileTypeMessage2": "is not a supported format.",
  "careers.modal.fileSizeTitle": "File Size Exceeded",
  "careers.modal.fileSizeMessage": "The file",
  "careers.modal.fileSizeMessage2": "exceeds the maximum size",
  "careers.modal.fileSizeMessage3": "limit.",
  "careers.modal.successTitle": "Application Received",
  "careers.modal.successMessage": "Your application has been successfully submitted. We appreciate your interest. Qualified candidates will be contacted by our human resources department.",
  "careers.modal.errorTitle": "Submission Error",
  "careers.modal.errorMessage": "An error occurred while submitting your application. Please verify your information and try again.",



    // Contact Subpage
    'contact.preTitle': 'Contact',
    'contact.title': 'Let\'s Connect',
    'contact.introText': 'We are available for new engagements. Please provide some details regarding your inquiry, and we will respond at our earliest convenience.',
    'contact.form.nameLabel': 'Full Name',
    'contact.form.emailLabel': 'Email Address',
    'contact.form.messageLabel': 'Message',
    'contact.form.submitButton': 'Send Message',
    'contact.details.email': 'contact@xhiva.org',
    'contact.details.phone': 'Available upon request',
    'contact.details.office': 'Suite 15, Beaufort Court, Admirals Way, Canary Wharf, London, E14 9XL, United Kingdom',   
     'contact.form.sendingButton': 'Sending...',
    'contact.modal.successTitle': 'Message Sent!',
    'contact.modal.successMessage': 'Thank you for contacting us. We will get back to you shortly.',
    'contact.modal.errorTitle': 'Submission Failed',
    'contact.modal.errorMessage': 'Oops! Something went wrong and your message could not be sent. Please try again or contact us directly.',

    // Footer Modals
    'footer.modal.disclaimer.title': 'Legal Disclaimer',
    'footer.modal.disclaimer.p1': 'This information is for illustrative purposes only and does not constitute an offer to sell or a solicitation of any offer to buy any securities or investment products.',
    'footer.modal.disclaimer.p2': 'All investments involve risk, including the possible loss of principal. Past performance is not indicative of future results. Projections and return targets are not guaranteed.',
    'footer.modal.disclaimer.p3': 'Access to these programmes is limited to qualified, sophisticated investors who meet strict eligibility criteria and have executed a formal legal agreement.',
    'footer.modal.privacy.title': 'Privacy Policy',
    'footer.modal.privacy.effectiveDate': 'Effective Date: 7 August 2025',
    'footer.modal.privacy.p1': 'This policy outlines how Xhiva Capital ("we", "us", "our") collects, uses, and safeguards the personal data you provide to us through our website. We act as the \'data controller\' for the purposes of the UK General Data Protection Regulation (UK GDPR).',
    'footer.modal.privacy.p2': 'We may collect information you provide via enquiry forms (name, email, investor status) and technical data (IP address, browser type). We use your data based on legitimate interests to respond to enquiries, consent for marketing, and legal obligation for AML/KYC requirements.',
    'footer.modal.privacy.p3': 'We do not sell your data but may share it with trusted third parties such as professional advisers, regulators, and service providers. Your data may be transferred outside the UK with appropriate safeguards in place.',
    'footer.modal.privacy.p4': 'We have implemented appropriate security measures and will retain data only as long as necessary. Under UK GDPR, you have rights to access, correct, erase, or object to the processing of your data, and to withdraw consent. For questions, please contact contact@xhiva.org.',
    'footer.modal.terms.title': 'Terms and Conditions',
    'footer.modal.terms.effectiveDate': 'Effective Date: 7 August 2025',
    'footer.modal.terms.p1': 'By accessing this website, you agree to be bound by these Terms and Conditions. The content is for informational purposes only and does not constitute financial, investment, legal, or other professional advice. Nothing on this site constitutes an offer or solicitation.',
    'footer.modal.terms.p2': 'All intellectual property is the property of Xhiva Capital. We shall not be liable for any loss or damage arising from your use of the site. All investments involve risk, and past performance is not indicative of future results.',
    'footer.modal.terms.p3': 'These terms are governed by the laws of England and Wales. For questions, contact info@xhiva.com.',



    // Disclaimer Modal
    'disclaimer.title': 'Legal Disclaimer',
    'disclaimer.content': 'Xhiva is a private global investment firm. The information on this website is for informational purposes only and does not constitute an offer to sell or a solicitation of an offer to buy any security or investment product. Any such offer or solicitation will be made only by means of a confidential private offering memorandum and in accordance with applicable securities laws. Past performance is not indicative of future results.',
  },
  es: {
    // Header - menu 
    'nav.services': 'Servicios',
    'nav.strategy': 'Estrategia',
    'nav.about': 'Sobre Nosotros',
    'nav.partnerships': 'Alianzas',
    'nav.governance': 'Gobernanza',
    'nav.funds': 'Fondos',
    'nav.careers': 'Carreras',
    'nav.contact': 'Contacto',
    'nav.getStarted': 'Comenzar',
    'nav.investment': 'Programas de Inversión',
    'nav.impact': 'Nuestro Impacto',
    'nav.protocol': 'Nuestro Protocolo de Compromiso',

    //--------------------------------HOMEPAGE--------------------------------
    // Hero
    'hero.title': 'Creando',
    'hero.title1': 'el Mundo',
    'hero.title2': 'del Mañana',
    'hero.description': "El futuro no se encuentra. Se construye. Xhiva despliega capital estratégico en las tecnologías disruptivas, infraestructura crítica e iniciativas sostenibles que definirán el próximo siglo. No solo invertimos en el mundo; invertimos en el mundo del mañana.",
    'hero.cta': 'Descubra Nuestro Impacto Global',
    'hero.viewDemo': 'Saber Más',

    'home.bridgeText': 'Impulsor del Progreso Global',

    // Homepage (Leadership Section)
    'homepage.leadership.subtitle': 'Nuestro Liderazgo',
    'homepage.leadership.title': 'Los Guardianes de Su Capital',
    'homepage.leadership.description': 'La confianza es la base de cada relación que construimos. Creemos que es esencial para nuestros socios conocer a las personas que están personalmente comprometidas con la salvaguardia de sus intereses y el mantenimiento de los principios de nuestra firma.',

    // About Us Section (Homepage)
    'about.subtitle': 'Arquitectos del Progreso Global',
    'about.description': "El capital es una corriente. La política es un timón. La innovación es el viento. Xhiva opera en la confluencia de los tres, navegando la complejidad global para redefinir industrias y construir valor generacional. No solo participamos en el mercado, nuestro objetivo es darle forma.",
    'about.learnMore': 'Saber Más',
    'about.feature1-title': "Liderazgo Global",
    'about.feature1-desc': "Liderando estrategias de inversión a nivel mundial con una inteligencia de mercado inigualable.",
    'about.feature2-title': "Excelencia Institucional",
    'about.feature2-desc': "Entregando resultados excepcionales para clientes institucionales y fondos soberanos.",
    'about.feature3-title': "Red de Expertos",
    'about.feature3-desc': "Profesionales de clase mundial que abarcan finanzas, tecnología y política en nuestras operaciones globales.",

    // Strategy Section (Homepage)
    'strategy.subtitle': 'ESTRATEGIA DE INVERSIÓN',
    'strategy.title': 'Un Marco Disciplinado para Oportunidades Exclusivas',
    'strategy.description': 'Nuestra estrategia de inversión está diseñada para inversores privados cualificados, family offices, individuos de patrimonio ultra alto, inversores institucionales y entidades soberanas que buscan acceso a programas de grado institucional dentro de un marco de cumplimiento robusto, preservación de capital y rendimiento ajustado al riesgo.',
    'strategy.card1.title': 'Originación Estratégica',
    'strategy.card1.description': 'Obtenemos oportunidades directamente a través de nuestra posición establecida con organismos soberanos e instituciones de primer nivel.',
    'strategy.card2.title': 'Evaluación y Escrutinio Prudencial',
    'strategy.card2.description': 'Realizamos un examen forense de los componentes estructurales, la procedencia de los activos, la integridad de la contraparte, el cumplimiento normativo y el entorno geopolítico.',
    'strategy.card3.title': 'Estructuras de Gobernanza a Medida',
    'strategy.card3.description': 'Construimos vehículos legales y financieros a medida con estricta adherencia a los estatutos y la integración de controles de preservación de capital.',
    'strategy.card4.title': 'Administración y Gobernanza Fiduciaria',
    'strategy.card4.description': 'Integración ESG con medición de impacto para la creación de valor responsable a largo plazo.',
    'strategy.image.alt': 'Estrategia de Fondos Globales',
    'strategy.image.title': 'Nuestro Marco Disciplinado de Cuatro Pilares',
    'strategy.image.description': 'Estos programas estructurados no se anuncian públicamente y solo son accesibles a través de un protocolo de compromiso formal.',
    'strategy.image.button': 'Descubrir más',

    // Interactive Section (Homepage)
    'interactive.title1': 'Capital con Visión.',
    'interactive.title2': 'Impacto con Propósito.',
    'interactive.description': "Creemos que el valor más profundo se crea en la intersección de ideas visionarias, capital estratégico e impacto global. No solo financiamos empresas, arquitectamos los cimientos del futuro.",
    'interactive.block1-title': 'Fundador y Socio Director',
    'interactive.block1-description': "Una biografía breve y digna que se centra en más de 20 años de experiencia en finanzas internacionales, roles anteriores en asesoría soberana o instituciones bancarias de primer nivel, y una frase final sobre su filosofía personal con respecto al capital paciente y la preservación del legado.",
    'interactive.block2-title': 'Jefe de Estructuración y Cumplimiento',
    'interactive.block2-description': "Una biografía que destaca una profunda experiencia en marcos regulatorios transfronterizos, estructuración legal para instrumentos financieros complejos y un compromiso con una gobernanza impecable como núcleo de la mitigación de riesgos.",
    'interactive.block3-title': 'Jefe de Originación Global',
    'interactive.block3-description': "Una biografía que detalla una extensa red global, experiencia en análisis geopolítico y la capacidad de obtener y examinar oportunidades únicas fuera del mercado con discreción y precisión.",

    // Carousel Section (Homepage)
    'carusel.block1-title': 'Arquitectura a Medida',
    'carusel.block1-description': 'Explore nuestra gama de servicios a medida, diseñados para las complejidades únicas de nuestros socios.',
    'carusel.block1-button': 'Descubrir Servicios',
    'carusel.block2-title': 'Los Motores del Mañana',
    'carusel.block2-description': 'Adéntrese en nuestra cartera de fondos especializados, cada uno diseñado para aprovechar una megatendencia global específica.',
    'carusel.block2-button': 'Explorar Fondos',
    'carusel.block3-title': 'Únase a la Vanguardia',
    'carusel.block3-description': "Somos un destino para el talento de élite del mundo. Descubra una carrera que lo sitúa en la frontera del progreso.",
    'carusel.block3-button': 'Ver Carreras',
    'carusel.block4-title': 'Alianzas Estratégicas',
    'carusel.block4-description': 'Forjamos alianzas poderosas para amplificar el impacto y crear valor sinérgico en todo nuestro ecosistema.',
    'carusel.block4-button': 'Conviértase en Socio',
    'carusel.block5-title': 'Gobernanza Basada en Principios',
    'carusel.block5-description': 'Nuestro compromiso con una gobernanza robusta y marcos éticos es la base de nuestra visión a largo plazo.',
    'carusel.block5-button': 'Aprender sobre Gobernanza',

    // Call to Action Section (Homepage)
    'cta.title.line1': 'COMIENCE SU',
    'cta.title.accent': 'VIAJE',
    'cta.description': "Únase a los inversores más sofisticados del mundo para acceder a oportunidades de inversión de grado institucional y soluciones de gestión de patrimonio personalizadas.",
    'cta.button.primary': 'SOLICITAR CONSULTA',
    'cta.button.secondary': 'EXPLORAR FONDOS',
    'cta.contact1.title': 'CONTACTO POR CORREO ELECTRÓNICO',
    'cta.contact1.text': 'investments@xhiva.com',
    'cta.contact2.title': 'CONTACTO TELEFÓNICO',
    'cta.contact2.text': 'Disponible bajo petición',
    'cta.contact3.title': 'OFICINAS GLOBALES',
    'cta.contact3.text': 'Seis continentes',
    'cta.notice.title': 'Acceso Institucional',
    'cta.notice.text': 'Los servicios de XHIVA están disponibles exclusivamente para inversores institucionales cualificados e individuos de alto patrimonio que cumplan con estrictos requisitos regulatorios y de umbral de inversión. Todas las inversiones están sujetas a una debida diligencia exhaustiva y evaluaciones de idoneidad.',

    // Footer Translations
    'footer.company': 'Empresa',
    'footer.investorRelations': 'Relaciones con Inversores',
    'footer.services': 'Organizaciones',
    'footer.globalFunds': 'Fondos Globales',
    'footer.legal': 'Legal',
    'footer.compliance': 'Cumplimiento',
    'footer.connect': 'Conectar',
    'footer.stakeholderLogin': 'Acceso para Interesados',
    'footer.globalOffices': 'Oficinas Globales',
    'footer.pressInquiries': 'Consultas de Prensa',
    'footer.logoAlt': 'Logo de XHIVA',
    'footer.logoText': 'XHIVA',
    'footer.brandDescription': 'Arquitectando el mundo del mañana a través de inversiones globales estratégicas y alianzas transformadoras.',
    'footer.newsletterTitle': 'Manténgase Informado',
    'footer.newsletterDescription': 'Reciba información exclusiva y actualizaciones sobre tendencias del mercado global y oportunidades de inversión.',
    'footer.emailPlaceholder': 'Ingrese su correo electrónico',
    'footer.subscribe': 'Suscribirse',
    'footer.newsletterNote': 'Solo para inversores institucionales y entidades cualificadas. Sujeto a verificación.',
    'footer.regulatedBy': 'Regulado por:',
    'footer.disclaimer': 'Aviso Legal',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.copyright': '© 2025 Xhiva. Todos los derechos reservados.',
    'footer.language.es': 'Español',
    'footer.language.en': 'English',

    //------------------------------------------------SUBPAGES-------------------------------------------------------
    //Protocol subpage : 
    'protocol.preTitle': 'Protocolo de Compromiso',
    'protocol.title': 'El Proceso de Incorporación del Cliente',
    'protocol.step1.title': 'Contacto Inicial',
    'protocol.step1.description': 'Envíe un formulario de consulta seguro detallando su estado de inversor.',
    'protocol.step2.title': 'Verificación de Elegibilidad',
    'protocol.step2.description': 'Realizamos verificaciones preliminares de KYC/AML para confirmar la cualificación.',
    'protocol.step3.title': 'Discusión Confidencial',
    'protocol.step3.description': 'Programe una llamada segura para discutir objetivos y alineación.',
    'protocol.step4.title': 'Acuerdo Formal',
    'protocol.step4.description': 'Ejecute NDAs y documentos legales para acceder al programa.',
    'protocol.step5.title': 'Ejecución del Programa',
    'protocol.step5.description': 'Participación estructurada con administración continua.',

    //INVESTMENT
    'investment.preTitle': 'Programas de Inversión',
    'investment.title': 'Acceso a Niveles de Inversión Exclusivos',
    'investment.intro1': 'Nuestra posición única dentro del panorama geopolítico y regulatorio global nos permite organizar el acceso a oportunidades de inversión estructuradas que normalmente se reservan para participantes de nivel institucional o soberano.',
    'investment.intro2': 'La participación es solo por invitación, después de un proceso exhaustivo de incorporación del cliente. Las siguientes categorías representan los tipos de programas con los que trabajamos, aunque la disponibilidad es dinámica y está sujeta a protocolos estrictos.',
    'investment.cta': 'Para explorar los programas disponibles, los inversores cualificados pueden iniciar nuestro Protocolo de Compromiso confidencial.',
    'investment.details.description': 'Descripción',
    'investment.details.access': 'Nivel de Acceso',
    'investment.details.duration': 'Duración Típica',
    'investment.details.risk': 'Perfil de Riesgo (Mitigado)',
    'investment.program1.title': 'Colocaciones Vinculadas a Bancos Centrales',
    'investment.program1.description': 'Estructuras seguras que ofrecen rendimientos consistentes y ajustados al riesgo basados en mecanismos respaldados por soberanos.',
    'investment.program1.access': 'Solo por invitación; prioridad soberana/institucional.',
    'investment.program1.duration': 'Mediano a largo plazo.',
    'investment.program1.risk': 'Bajo; con énfasis en la preservación del capital.',
    'investment.program2.title': 'Programas de Trading Afiliados a Gobiernos',
    'investment.program2.description': 'Vinculado a plataformas reguladas que apoyan iniciativas de financiación nacional.',
    'investment.program2.access': 'Restringido a entidades cualificadas.',
    'investment.program2.duration': 'Variable, alineado con los mandatos.',
    'investment.program2.risk': 'Moderado; con salvaguardas regulatorias.',
    'investment.program3.title': 'Programas Piloto y de Acceso Limitado',
    'investment.program3.description': 'Oportunidades innovadoras en etapa temprana con términos únicos y potencial de crecimiento.',
    'investment.program3.access': 'Por invitación especial.',
    'investment.program3.duration': 'Corto a mediano plazo.',
    'investment.program3.risk': 'Más alto; compensado por mitigaciones a medida.',
    'investment.program4.title': "Programas a Plazo Fijo o 'Bullet'",
    'investment.program4.description': 'Potencial de alto rendimiento durante períodos definidos; sensible al tiempo.',
    'investment.program4.access': 'Altamente selectivo.',
    'investment.program4.duration': 'Corto plazo.',
    'investment.program4.risk': 'Variable; incluye indemnizaciones cuando sea aplicable.',

    //Impact  page 
    'impact.preTitle': 'Nuestro Impacto',
    'impact.title': 'Un Mandato Más Allá del Beneficio: Fomentando la Estabilidad y el Progreso',
    'impact.intro1': 'Creemos que la forma más sofisticada de inversión es aquella que logra un doble mandato: el crecimiento inteligente del capital y el avance deliberado de la sociedad. Nuestro propósito se define por esta sinergia.',
    'impact.intro2': 'Nuestro impacto no es una ocurrencia tardía; está integrado en nuestra estrategia de originación. Buscamos oportunidades donde el capital se pueda desplegar para:',
    'impact.conclusion': 'Para nuestros clientes, este enfoque significa que su capital es parte de un legado más grande y significativo, uno que construye valor duradero para sus carteras y para el mundo.',
    'impact.economic.title': 'Reforzar las Bases Económicas',
    'impact.economic.description': 'Al participar en programas que apoyan la gestión de la riqueza soberana y las iniciativas de financiación nacional, contribuimos a la estabilidad a largo plazo que es esencial para que las naciones prosperen. Esto puede implicar la modernización de infraestructuras críticas o el fortalecimiento de la capacidad comercial de un país.',
    'impact.humanitarian.title': 'Permitir el Progreso Humanitario',
    'impact.humanitarian.description': 'Alineamos nuestros esfuerzos con objetivos reconocidos a nivel mundial, como los descritos en los Objetivos de Desarrollo Sostenible de la ONU. Nuestra participación puede canalizar un capital significativo hacia iniciativas que tienen un efecto tangible y positivo en el bienestar social, desde avances en la salud pública hasta mejoras en la seguridad alimentaria.',

    // About Us Subpage
    'about.page.preTitle': 'Sobre Nosotros',
    'about.page.mainTitle': 'Arquitectos de Estabilidad y Valor en la Cima de las Finanzas Globales',
    'about.page.title':'Nuestra Posición en las Finanzas Globales',
    'about.page.intro1': 'Bienvenidos. Operamos en la confluencia de la banca central, las iniciativas de gobiernos soberanos y el capital privado. Con una presencia operativa en más de 63 jurisdicciones, nuestra firma desempeña un papel fundamental en la arquitectura financiera global.',
    'about.page.intro2': 'Nuestros compromisos requieren con frecuencia que actuemos en capacidades fiduciarias como agente de depósito en garantía, supervisor de cumplimiento o socio estructurador para entidades soberanas e instituciones financieras reguladas de primer nivel. Esta posición única nos otorga un acceso privilegiado a oportunidades que, por su naturaleza, no están disponibles en los mercados públicos.',
    'about.philosophy.title': 'Una Filosofía de Administración',
    'about.philosophy.text': 'El capital es más que una mercancía; es un catalizador. En las manos adecuadas, guiado por una filosofía disciplinada, tiene el poder no solo de crecer, sino de construir, estabilizar y perdurar por generaciones. Nuestra firma se fundó sobre este principio. Creemos que la verdadera administración se extiende más allá de la entrega de rendimientos ajustados al riesgo; exige un compromiso inquebrantable con la preservación del legado y la creación de un impacto positivo y duradero. No solo gestionamos activos; entramos en alianzas a largo plazo basadas en la confianza, la discreción y una comprensión compartida de lo que significa construir un valor resiliente en un mundo complejo.',
    'about.mission.title': 'Nuestra Misión',
    'about.mission.text1': 'Nuestra Misión es doble: estructurar y entregar programas de inversión impecablemente gobernados que proporcionen rendimientos medidos y ajustados al riesgo, al tiempo que cumplen con mandatos más amplios para la estabilización económica y un impacto humanitario significativo.',
    'about.mission.text2': 'Cada acción que tomamos está guiada por tres principios inquebrantables:',
    'about.principles.item1.title': 'Diligencia Debida Rigurosa',
    'about.principles.item1.text': 'Investigamos meticulosamente cada oportunidad, escudriñando la procedencia de los activos, la integridad de la contraparte y el contexto geopolítico.',
    'about.principles.item2.title': 'Transparencia Inquebrantable',
    'about.principles.item2.text': 'Creemos que la confianza se construye sobre la claridad. Nuestros clientes reciben informes transparentes dentro de los límites de los acuerdos de confidencialidad.',
    'about.principles.item3.title': 'Cumplimiento Inflexible',
    'about.principles.item3.text': 'La adhesión a los más altos estándares internacionales de cumplimiento normativo no es simplemente una política, es la base de nuestras operaciones.',
    'about.page.footer': 'Somos más que gestores de activos; somos administradores de confianza del capital, dedicados a construir un valor resiliente para nuestra selecta clientela.',



    // Services Subpage
    'services.preTitle': 'SERVICIOS INSTITUCIONALES',
    'services.title': 'Una Suite Integrada de Servicios Financieros',
    'services.details.focusTitle': 'Enfoque',
    'services.details.approachTitle': 'Metodología',
    'services.details.deliveryTitle': 'Entrega',
    'services.item1.title': 'Gestión de Activos',
    'services.item1.subtitle': 'Soluciones de Cartera',
    'services.item1.description': 'Gestión sofisticada de carteras globales diversificadas con estrategias de grado institucional.',
    'services.item1.details.focus': 'Gestión Integral de Inversiones',
    'services.item1.details.approach': 'Construcción de carteras multiactivo, reequilibrio dinámico y marcos de riesgo avanzados.',
    'services.item1.details.delivery': 'Informes de grado institucional en tiempo real y gestión de relaciones dedicada.',
    'services.item2.title': 'Construcción de Cartera a Medida',
    'services.item2.subtitle': 'Soluciones a Medida',
    'services.item2.description': 'Estrategias de inversión a medida diseñadas para alinearse con objetivos y perfiles de riesgo únicos.',
    'services.item2.details.focus': 'Arquitectura de Inversión Personalizada',
    'services.item2.details.approach': 'Optimización con aprendizaje automático, estrategias fiscalmente eficientes e integración de inversiones alternativas.',
    'services.item2.details.delivery': 'Programas de informes personalizados con gestores dedicados y canales de comunicación directos.',
    'services.item3.title': 'Planificación Patrimonial y Sucesoria',
    'services.item3.subtitle': 'Soluciones de Legado',
    'services.item3.description': 'Soluciones estratégicas de preservación y transferencia de patrimonio diseñadas para un impacto multigeneracional.',
    'services.item3.details.focus': 'Estrategias de Patrimonio Generacional',
    'services.item3.details.approach': 'Implementación de fideicomisos dinásticos, optimización de la planificación patrimonial y estructuras sofisticadas de mitigación fiscal.',
    'services.item3.details.delivery': 'Revisiones estratégicas anuales con evaluaciones trimestrales y equipos dedicados de family office.',
    'services.item4.title': 'Servicios Fiduciarios y de Fideicomiso',
    'services.item4.subtitle': 'Administración Institucional',
    'services.item4.description': 'Supervisión fiduciaria profesional que proporciona una gobernanza de nivel institucional para estructuras complejas.',
    'services.item4.details.focus': 'Administración de Activos Institucionales',
    'services.item4.details.approach': 'Servicios de fideicomisario corporativo con supervisión del comité de inversiones y cumplimiento normativo integral.',
    'services.item4.details.delivery': 'Monitoreo continuo con supervisión en tiempo real y acceso directo a profesionales fiduciarios de alto nivel.',
    'services.item5.title': 'Inversión de Impacto y ESG',
    'services.item5.subtitle': 'Integración Sostenible',
    'services.item5.description': 'Marcos avanzados de integración ESG y medición de impacto que ofrecen rendimientos medibles.',
    'services.item5.details.focus': 'Integración de Inversión Sostenible',
    'services.item5.details.approach': 'Puntuación ESG propia, medición integral del impacto y evaluación del riesgo climático.',
    'services.item5.details.delivery': 'Informes de impacto semestrales, actualizaciones trimestrales y especialistas ESG dedicados.',
    'services.item6.title': 'Coinversión Directa',
    'services.item6.subtitle': 'Acceso Exclusivo',
    'services.item6.description': 'Acceso privilegiado a oportunidades de inversión propias normalmente reservadas para instituciones.',
    'services.item6.details.focus': 'Acceso a Acuerdos Exclusivos',
    'services.item6.details.approach': 'Coinversiones de capital privado con estructuras de comisiones reducidas y participación en proyectos de infraestructura.',
    'services.item6.details.delivery': 'Acuerdo por acuerdo, despliegue rápido y acceso prioritario a oportunidades propias.',

    // Funds Subpage
    'funds.subtitle': 'NUESTROS FONDOS GLOBALES',
    'funds.title': 'Los Motores del Progreso Global',
    'funds.description': 'Una cartera curada de vehículos de inversión especializados, cada uno diseñado para capitalizar una megatendencia global distinta. Nuestros fondos brindan a los inversores cualificados acceso a estrategias propias y oportunidades de grado institucional en todo el espectro de riesgo-rendimiento.',
    'funds.videoFallback': 'Su navegador no soporta la etiqueta de video.',
    'funds.details.philosophy': 'Filosofía',
    'funds.details.strategy': 'Estrategia Principal',
    'funds.details.allocation': 'Asignación Primaria',
    'funds.details.financials': 'Finanzas',
    'funds.details.riskProfile': 'Perfil de Riesgo',
    'funds.details.horizon': 'Horizonte',
    'funds.details.targetIRR': 'TIR Objetivo',
    'funds.item1.name': 'El Fondo de Crecimiento Génesis',
    'funds.item1.focus': 'Empresas de tecnología disruptiva en etapa temprana',
    'funds.item1.philosophy': 'Creemos que los rendimientos más significativos se generan invirtiendo temprano en tecnologías que remodelan fundamentalmente las industrias. Nuestra tesis se basa en identificar fundadores visionarios y proporcionar el capital y la orientación estratégica para lograr un crecimiento exponencial.',
    'funds.item1.strategy': 'Inversiones de capital de riesgo y capital de crecimiento en IA, computación cuántica y biología sintética.',
    'funds.item1.allocation': 'Principalmente acciones no públicas y notas convertibles.',
    'funds.item1.riskProfile': 'Alto',
    'funds.item1.investmentHorizon': '10+ Años',
    'funds.item1.targetIRR': '30-35% (neto)',
    'funds.item2.name': 'El Fondo de Infraestructura Soberana',
    'funds.item2.focus': 'Proyectos de infraestructura a gran escala gubernamentales y público-privados',
    'funds.item2.philosophy': 'La civilización moderna se construye sobre una base de infraestructura confiable. Buscamos generar rendimientos estables a largo plazo financiando los activos esenciales que impulsan las economías, desde redes digitales hasta redes de energía sostenible.',
    'funds.item2.strategy': 'Financiamiento directo y coinversión en transporte, redes energéticas e infraestructura digital.',
    'funds.item2.allocation': 'Mezcla de deuda a largo plazo, capital privado y activos reales.',
    'funds.item2.riskProfile': 'Bajo-Moderado',
    'funds.item2.investmentHorizon': '15-20 Años',
    'funds.item2.targetIRR': '8-12% (neto)',
    'funds.item3.name': 'El Fondo de Impacto Global',
    'funds.item3.focus': 'Proyectos humanitarios y de desarrollo sostenible',
    'funds.item3.philosophy': 'Sostenemos que el éxito financiero y el cambio social positivo no son mutuamente excluyentes. Este fondo se dirige a empresas que proporcionan mejoras medibles en el bienestar humano y la sostenibilidad ambiental, al tiempo que ofrecen rendimientos competitivos.',
    'funds.item3.strategy': 'Inversión en energía renovable, seguridad alimentaria y acceso a la atención médica en mercados emergentes.',
    'funds.item3.allocation': 'Mezcla de bonos de impacto social, capital privado y bienes raíces sostenibles.',
    'funds.item3.riskProfile': 'Moderado',
    'funds.item3.investmentHorizon': '7-10 Años',
    'funds.item3.targetIRR': '15-18% (neto)',
    'funds.item4.name': 'El Fondo Quantum Alpha',
    'funds.item4.focus': 'Trading cuantitativo y algorítmico avanzado',
    'funds.item4.philosophy': 'Los mercados globales son un sistema complejo de información. Al aprovechar la IA sofisticada y los modelos cuantitativos, nuestro objetivo es identificar y capitalizar las ineficiencias transitorias del mercado que son invisibles para el ojo humano.',
    'funds.item4.strategy': 'Modelos impulsados por IA para identificar ineficiencias del mercado en los mercados de capitales globales.',
    'funds.item4.allocation': 'Cartera multiactivo que incluye acciones, renta fija, divisas y materias primas.',
    'funds.item4.riskProfile': 'Alto',
    'funds.item4.investmentHorizon': 'Corto a Mediano Plazo',
    'funds.item4.targetIRR': '20-25% (impulsado por Alfa)',
    'funds.item5.name': 'El Fondo de Activos Reales y Materias Primas',
    'funds.item5.focus': 'Activos tangibles con valor intrínseco',
    'funds.item5.philosophy': 'En un mundo cada vez más digital, los activos tangibles proporcionan una reserva fundamental de valor y una cobertura contra la inflación. Este fondo asegura la propiedad de recursos críticos del mundo real que son esenciales para la industria y el consumo global.',
    'funds.item5.strategy': 'Adquisición estratégica en energía, metales preciosos y agricultura.',
    'funds.item5.allocation': 'Principalmente materias primas físicas, bienes raíces y contratos de futuros.',
    'funds.item5.riskProfile': 'Moderado-Alto',
    'funds.item5.investmentHorizon': '5-10 Años',
    'funds.item5.targetIRR': '12-16% (neto)',
    'funds.item6.name': 'El Fondo Bio-Revolución',
    'funds.item6.focus': 'Soluciones de biotecnología y atención médica de próxima generación',
    'funds.item6.philosophy': 'La convergencia de la biología y la tecnología está creando una ola de innovación sin precedentes en la salud humana. Invertimos en empresas a la vanguardia de esta revolución, apuntando a avances en longevidad, medicina personalizada y erradicación de enfermedades.',
    'funds.item6.strategy': 'Inversiones en edición de genes, medicina personalizada y tecnologías de extensión de la vida.',
    'funds.item6.allocation': 'Mezcla de capital de riesgo, acciones públicas e instrumentos que devengan regalías.',
    'funds.item6.riskProfile': 'Muy Alto',
    'funds.item6.investmentHorizon': '10-15 Años',
    'funds.item6.targetIRR': '35%+ (neto)',
    'funds.item7.name': 'El Fondo de la Frontera Digital',
    'funds.item7.focus': 'Arquitectura de la internet de próxima generación',
    'funds.item7.philosophy': 'La descentralización y la propiedad digital son los pilares fundamentales de la próxima era de internet. Invertimos en los protocolos, la infraestructura y las aplicaciones centrales que impulsarán esta nueva economía digital más equitativa.',
    'funds.item7.strategy': 'Inversión en DeFi, infraestructura de blockchain y tecnologías de ciberseguridad.',
    'funds.item7.allocation': 'Principalmente activos digitales, capital de riesgo y capital privado.',
    'funds.item7.riskProfile': 'Muy Alto',
    'funds.item7.investmentHorizon': '7-10 Años',
    'funds.item7.targetIRR': '40%+ (neto)',
    'funds.item8.name': 'El Fondo de Estabilidad Global',
    'funds.item8.focus': 'Preservación de capital y mitigación de riesgos',
    'funds.item8.philosophy': 'La preservación de la riqueza es la piedra angular de la prosperidad duradera. Este fondo está diseñado para proteger el capital y proporcionar rendimientos estables en todos los ciclos del mercado, actuando como un ancla defensiva para una cartera diversificada.',
    'funds.item8.strategy': 'Fondo multiactivo para todas las condiciones del mercado con deuda soberana y activos de refugio seguro.',
    'funds.item8.allocation': 'Mezcla equilibrada de bonos del gobierno, valores vinculados a la inflación y acciones defensivas.',
    'funds.item8.riskProfile': 'Bajo',
    'funds.item8.investmentHorizon': 'Largo Plazo',
    'funds.item8.targetIRR': '5-7% (neto)',
    'funds.item9.name': 'El Fondo de Ascendencia de Mercados Emergentes',
    'funds.item9.focus': 'Economías de alto crecimiento',
    'funds.item9.philosophy': "El centro de gravedad económico del mundo está cambiando. Identificamos e invertimos en la próxima generación de líderes de la industria en Asia, África y América Latina, capitalizando los cambios demográficos y el rápido crecimiento de la clase consumidora.",
    'funds.item9.strategy': 'Identificación de los líderes de la industria de la próxima ola en Asia, África y América Latina.',
    'funds.item9.allocation': 'Mezcla de acciones públicas y privadas, deuda soberana y bienes raíces.',
    'funds.item9.riskProfile': 'Alto',
    'funds.item9.investmentHorizon': '8-12 Años',
    'funds.item9.targetIRR': '22-28% (neto)',

    
"careers.preTitle": "ÚNETE A LA REVOLUCIÓN",
"careers.title": "Forja el Futuro de las Finanzas con Nosotros",
"careers.introText": "Buscamos profesionales ambiciosos y con visión de futuro, listos para desafiar el status quo. Si prosperas en un entorno definido por la confianza, la innovación y el impacto global, tu próximo paso profesional está aquí.",

"careers.block1.title": "Ambiente Innovador",
"careers.block1.text": "Trabaja junto a mentes pioneras desarrollando soluciones y tecnologías financieras de próxima generación.",

"careers.block2.title": "Impacto Global",
"careers.block2.text": "Contribuye a una plataforma que influye en el crecimiento económico real y la estabilidad en todos los continentes.",

"careers.block3.title": "Cultura de Confianza",
"careers.block3.text": "Benefíciate de un lugar de trabajo de apoyo, ético y transparente donde la integridad es primordial.",

"careers.form.heading": "Aplica Hoy",
"careers.form.nameLabel": "Nombre Completo",
"careers.form.emailLabel": "Correo Electrónico",
"careers.form.positionLabel": "Puesto Deseado",
"careers.form.coverLetterLabel": "Carta de Presentación / Mensaje",
"careers.form.fileTitle": "Adjuntar Documentos (Máx. 5)",
"careers.form.selectFiles": "Seleccionar Archivos",
"careers.form.limitReached": "Límite Alcanzado",
"careers.form.submitButton": "Enviar Solicitud",
"careers.form.sendingButton": "Enviando...",

"careers.modal.limitTitle": "Límite de Archivos Alcanzado",
"careers.modal.limitMessage": "Solo puedes subir un máximo de 5 archivos.",
"careers.modal.successTitle": "¡Solicitud Enviada!",
"careers.modal.successMessage": "Gracias por tu interés. Hemos recibido tu solicitud.",
"careers.modal.errorTitle": "Fallo en la Solicitud",
"careers.modal.errorMessage": "Ocurrió un error al enviar tu solicitud. Por favor, inténtalo de nuevo.",



    // Partnerships Subpage
    'partnerships.preTitle': 'MÁS ALLÁ DE LAS FRONTERAS',
    'partnerships.title': 'Red Global de Alianzas',
    'partnerships.item1.category': 'FONDOS SOBERANOS DE RIQUEZA',
    'partnerships.item1.description': 'Alianzas estratégicas con autoridades de inversión nacionales y entidades soberanas en las principales economías.',
    'partnerships.item1.focus': 'Relaciones Gubernamentales',
    'partnerships.item2.category': 'INVERSORES INSTITUCIONALES',
    'partnerships.item2.description': 'Relaciones de colaboración con fondos de pensiones, dotaciones y compañías de seguros en todo el mundo.',
    'partnerships.item2.focus': 'Capital Institucional',
    'partnerships.item3.category': 'BANCOS GLOBALES',
    'partnerships.item3.description': 'Alianzas bancarias centrales con instituciones financieras de primer nivel para el acceso a los mercados de capitales.',
    'partnerships.item3.focus': 'Infraestructura Bancaria',
    'partnerships.item4.category': 'SOCIOS TECNOLÓGICOS',
    'partnerships.item4.description': 'Alianzas de innovación con empresas líderes de fintech y proveedores de infraestructura tecnológica.',
    'partnerships.item4.focus': 'Innovación Digital',
    'partnerships.item5.category': 'ORGANISMOS REGULADORES',
    'partnerships.item5.description': 'Alianzas de cumplimiento con las autoridades reguladoras financieras en todas las jurisdicciones operativas.',
    'partnerships.item5.focus': 'Excelencia Regulatoria',
    'partnerships.item6.category': 'INSTITUCIONES DE INVESTIGACIÓN',
    'partnerships.item6.description': 'Alianzas académicas con universidades y think tanks líderes para la investigación y el análisis de mercado.',
    'partnerships.item6.focus': 'Excelencia en Investigación',
    'partnerships.cta.title': '¿Listo para Construir el Futuro?',
    'partnerships.cta.subtitle': "Colaboremos y creemos valor juntos. Buscamos socios innovadores para unirse a nuestra misión.",
    'partnerships.cta.button': 'Conviértase en Socio',

    //Strategy subpage
    'strategy.page.preTitle': 'Nuestras Estrategias',
    'strategy.page.title': 'Nuestra Estrategia de Inversión',
    'strategy.page.subtitle': 'Un Marco Disciplinado para Oportunidades Exclusivas',
    'strategy.page.intro': 'Nuestra estrategia de inversión está diseñada para inversores privados cualificados, family offices e individuos de alto patrimonio que buscan acceso a programas de grado institucional dentro de un marco de cumplimiento robusto, preservación de capital y un rendimiento excepcional ajustado al riesgo.',
    'strategy.page.disclaimer': 'Estos programas estructurados no se anuncian públicamente y solo son accesibles a través de un protocolo de compromiso formal.',
    'strategy.approach.title': 'Nuestro Enfoque Estratégico',
    'strategy.approach.intro': 'Nuestra estrategia no se basa en la especulación del mercado, sino en el acceso disciplinado a programas financieros de alto nivel previamente examinados. Cada compromiso potencial se evalúa por sus propios méritos, con un enfoque en:',
    'strategy.approach.item1.title': 'Procedencia y Seguridad de los Activos',
    'strategy.approach.item1.description': 'Comenzamos verificando el origen y la integridad de todos los activos, asegurando una base limpia y conforme para cualquier transacción.',
    'strategy.approach.item2.title': 'Alineación Regulatoria',
    'strategy.approach.item2.description': 'Nuestras estructuras están diseñadas para cumplir y superar las obligaciones regulatorias de todas las jurisdicciones participantes, asegurando una ejecución fluida y segura.',
    'strategy.approach.item3.title': 'Coincidencia de Objetivos Estratégicos',
    'strategy.approach.item3.description': 'Trabajamos para comprender los objetivos centrales de nuestras contrapartes, ya sea la estabilización de la riqueza soberana o el crecimiento del capital privado, y alineamos nuestros programas en consecuencia.',
    'strategy.governance.title': 'Gobernanza, Riesgo y Estructuración',
    'strategy.governance.intro': 'Si bien ninguna inversión está completamente libre de riesgos, todo nuestro modelo operativo está diseñado para mitigar dichos riesgos. Todos los programas que organizamos se estructuran en colaboración directa con instituciones financieras reguladas, operadores de plataformas con licencia y, en muchos casos, entidades gubernamentales. Nuestro compromiso de proteger los intereses de los clientes incluye:',
    'strategy.governance.item1.title': 'Diligencia Debida Robusta',
    'strategy.governance.item1.description': 'Verificaciones de antecedentes exhaustivas y protocolos de cumplimiento para todas las partes.',
    'strategy.governance.item2.title': 'Protocolos de Financiación Transparentes',
    'strategy.governance.item2.description': 'Verificación clara del origen y la propiedad de los fondos (KYC/AML).',
    'strategy.governance.item3.title': 'Estructuración de Capital a Medida',
    'strategy.governance.item3.description': 'Vehículos legales y financieros a medida diseñados para un cumplimiento normativo óptimo y la protección de activos.',
    'strategy.govergannce.item4.title': 'Mitigación de Riesgos Opcional',
    'strategy.governance.item4.description': 'Acceso a mecanismos como la supervisión de terceros, indemnizaciones y otras salvaguardas institucionales.',
    'strategy.conclusion.text': 'Cuando es necesario, nuestro equipo está equipado para asesorar y establecer las entidades legales y financieras apropiadas para cumplir con objetivos jurisdiccionales o estratégicos específicos, asegurando que nuestros clientes estén perfectamente posicionados para la participación.',

    // Contact Subpage
    'contact.preTitle': 'Contacto',
    'contact.title': 'Conectemos',
    'contact.introText': 'Estamos disponibles para nuevos compromisos. Proporcione algunos detalles sobre su consulta y le responderemos a la brevedad posible.',
    'contact.form.nameLabel': 'Nombre Completo',
    'contact.form.emailLabel': 'Dirección de Correo Electrónico',
    'contact.form.messageLabel': 'Mensaje',
    'contact.form.submitButton': 'Enviar Mensaje',
    'contact.details.email': 'contact@xhiva.org ',
    'contact.details.phone': 'Disponible bajo petición',
    'contact.details.office': 'Suite 15, Beaufort Court, Admirals Way, Canary Wharf, London, E14 9XL, United Kingdom',
    
    'contact.form.sendingButton': 'Enviando...',
    'contact.modal.successTitle': '¡Mensaje Enviado!',
    'contact.modal.successMessage': 'Gracias por contactarnos. Nos pondremos en contacto contigo en breve.',
    'contact.modal.errorTitle': 'Envío Fallido',
    'contact.modal.errorMessage': '¡Ups! Algo salió mal y tu mensaje no pudo ser enviado. Por favor, inténtalo de nuevo o contáctanos directamente.',


    // Footer Modals
    'footer.modal.disclaimer.title': 'Aviso Legal',
    'footer.modal.disclaimer.p1': 'Esta información es solo para fines ilustrativos y no constituye una oferta de venta ni una solicitud de oferta de compra de valores o productos de inversión.',
    'footer.modal.disclaimer.p2': 'Todas las inversiones implican un riesgo, incluida la posible pérdida del principal. El rendimiento pasado no es indicativo de resultados futuros. Las proyecciones y los objetivos de rendimiento no están garantizados.',
    'footer.modal.disclaimer.p3': 'El acceso a estos programas está limitado a inversores cualificados y sofisticados que cumplan con estrictos criterios de elegibilidad y hayan ejecutado un acuerdo legal formal.',
    'footer.modal.privacy.title': 'Política de Privacidad',
    'footer.modal.privacy.effectiveDate': 'Fecha de Entrada en Vigor: 7 de agosto de 2025',
    'footer.modal.privacy.p1': 'Esta política describe cómo Xhiva Capital ("nosotros", "nuestro") recopila, utiliza y protege los datos personales que nos proporciona a través de nuestro sitio web. Actuamos como el "controlador de datos" a los efectos del Reglamento General de Protección de Datos del Reino Unido (UK GDPR).',
    'footer.modal.privacy.p2': 'Podemos recopilar la información que proporciona a través de formularios de consulta (nombre, correo electrónico, estado del inversor) y datos técnicos (dirección IP, tipo de navegador). Utilizamos sus datos en función de intereses legítimos para responder a las consultas, el consentimiento para el marketing y la obligación legal para los requisitos de AML/KYC.',
    'footer.modal.privacy.p3': 'No vendemos sus datos, pero podemos compartirlos con terceros de confianza como asesores profesionales, reguladores y proveedores de servicios. Sus datos pueden ser transferidos fuera del Reino Unido con las salvaguardias adecuadas.',
    'footer.modal.privacy.p4': 'Hemos implementado medidas de seguridad adecuadas y retendremos los datos solo el tiempo que sea necesario. Según el UK GDPR, tiene derecho a acceder, corregir, borrar u oponerse al procesamiento de sus datos, y a retirar el consentimiento. Si tiene preguntas, comuníquese con contact@xhiva.org.',
    'footer.modal.terms.title': 'Términos y Condiciones',
    'footer.modal.terms.effectiveDate': 'Fecha de Entrada en Vigor: 7 de agosto de 2025',
    'footer.modal.terms.p1': 'Al acceder a este sitio web, usted acepta estar sujeto a estos Términos y Condiciones. El contenido es solo para fines informativos y no constituye asesoramiento financiero, de inversión, legal u otro profesional. Nada en este sitio constituye una oferta o solicitud.',
    'footer.modal.terms.p2': 'Toda la propiedad intelectual es propiedad de Xhiva Capital. No seremos responsables de ninguna pérdida o daño que surja del uso del sitio. Todas las inversiones implican un riesgo, y el rendimiento pasado no es indicativo de resultados futuros.',
    'footer.modal.terms.p3': 'Estos términos se rigen por las leyes de Inglaterra y Gales. Si tiene preguntas, comuníquese con info@xhiva.com.',

    // Disclaimer Modal
    'disclaimer.title': 'Aviso Legal',
    'disclaimer.content': 'Xhiva es una firma de inversión global privada. La información en este sitio web es solo para fines informativos y no constituye una oferta de venta ni una solicitud de oferta de compra de ningún valor o producto de inversión. Cualquier oferta o solicitud de este tipo se realizará únicamente por medio de un memorando de oferta privada confidencial y de acuerdo con las leyes de valores aplicables. El rendimiento pasado no es indicativo de resultados futuros.',
  }
};


// --- TYPE DEFINITIONS ---
type Language = 'en' | 'es';
export type TranslationKey = keyof typeof translations['en'];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

// --- CONTEXT & PROVIDER ---
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Check if localStorage is available (for server-side rendering safety)
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('appLanguage') as Language;
      return savedLanguage || 'en';
    }
    return 'en';
  });

  // --- FIX: Use useEffect to save the language to localStorage whenever it changes ---
  useEffect(() => {
    localStorage.setItem('appLanguage', language);
  }, [language]);

  // Create a new setLanguage function to update both state and localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: TranslationKey): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// --- CUSTOM HOOK ---
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}